# Generated by Django 4.0.5 on 2022-07-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_cia', models.CharField(max_length=15)),
                ('producto_codigo', models.CharField(max_length=10)),
                ('producto_descripcion', models.CharField(max_length=30)),
                ('producto_cantidad', models.IntegerField(null=0)),
                ('producto_costo', models.IntegerField(null=0)),
                ('producto_fecha', models.DateTimeField(null=True)),
            ],
        ),
    ]
