# Generated by Django 4.0.5 on 2022-07-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=30)),
                ('edad_familiar', models.IntegerField()),
                ('documento_familiar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoCia', models.CharField(max_length=15)),
                ('productoCodigo', models.CharField(max_length=10)),
                ('productoDescripcion', models.CharField(max_length=30)),
                ('productoCantidad', models.IntegerField(null=0)),
                ('productoCosto', models.IntegerField(null=0)),
            ],
        ),
    ]
