# Generated by Django 4.0.5 on 2022-07-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_cia', models.CharField(max_length=15)),
                ('producto_codigo', models.CharField(max_length=10)),
                ('producto_descripcion', models.CharField(max_length=30)),
                ('producto_cantidad', models.IntegerField(null=0)),
            ],
        ),
    ]
